#!/usr/bin/env bash
#moving permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\t\trewrite ^\/redirect_me https:\/\/github.com\/Sadickachuli permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
