#!/usr/bin/env bash
#changing the 404 page

sudo apt update
sudo apt install nginx -y
sudo touch /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Holberton School" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        index index.html;
        error_page 404 /404.html;

        server_name _;

        location /redirect_me {
           return 301 https:/https://github.com/falyseck/;
        }
}
" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
